### ISSUE TITLE
Spotify card showing the Twitch purple color

### ISSUE THREAD

**Issue by tbc02** [mr-miner1/cooler-activity-status#2]
I've tried rewriting some variables in the theme[bd].theme.css file, but I haven't been able to fix it. Not sure if I'm just dumb and it's meant to be like this, but I'd assume it's not. I'm using Powercord.
![image](https://user-images.githubusercontent.com/88152663/127516661-8b9bb1c3-0911-443f-ad32-f052388ae807.png)

**Comment by tbc02** [comment]
Edited the wrong file, should have edited the .scss file. Still worth noting that it doesn't work by default, though.

**Comment by mr-miner1** [comment]
what did u edit to fix @tbc02

**Comment by tbc02** [comment]
The file was "theme.scss" I think, I had to open it in Dreamweaver. I'm not on my computer and I don't remember the exact names of things, but at the start of the file there's a lot of variables for platforms, and each have a hex code ezcep for Spotify. Spotify's is set to be "Spotify--color" or something, so I just changed that to the actual Spotify hex code you can Google and find.

**Comment by mr-miner1** [comment]
yea i think the problem is if you dont have the spotify powercord plugin enabled the variable doesnt exist, thanks!
